version: 2.1
commands:
  run_tests_linux:
    description: "Build tesladon and run the test suite"
    parameters:
      version:
        type: string
    steps:
      - run: sudo apt install cmake    
      - run_tests:
          version: << parameters.version >>
          os: "linux"
  run_tests:
    description: "Build tesladon and run the test suite"
    parameters:
      version:
        type: string
      os:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-<< parameters.os >>-<< parameters.version >>-{{ checksum "package.json" }}
          - v1-dependencies-<< parameters.os >>-<< parameters.version >>-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-<< parameters.os >>-<< parameters.version >>-{{ checksum "package.json" }}
          
      - run: mkdir -p circleci-test-results/eslint
      - run: mkdir -p circleci-test-results/xunit
      - run: npm run eslint -- **/*.js -f junit -o circleci-test-results/eslint/eslint.xml
      - run: set -eo pipefail && npm test | npm run tap-xunit > circleci-test-results/xunit/results.xml
        
      - store_test_results:
          path: circleci-test-results
      - store_artifacts:
          path: circleci-artifacts
      - store_artifacts:
          path: circleci-test-results
jobs:
  linux-node-14:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - run_tests_linux:
          version: "14"
  linux-node-12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - run_tests_linux:
          version: "12"
  linux-node-10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - run_tests_linux:
          version: "10"
  linux-node-8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - run_tests_linux:
          version: "8"
workflows:
  version: 2
  build:
    jobs:
      - linux-node-14
      - linux-node-12
      - linux-node-10
      - linux-node-8